### ISSUE TITLE
Cannot be able to close navigation bar even if clicked to hamburger menu

### ISSUE THREAD

**Issue by afozbek** [sdras/career-ladders#1]
As title goes user cannot be able to close navigation menu.

![image](https://user-images.githubusercontent.com/37661157/114906440-b18fcc80-9e22-11eb-8b82-5f918c8ecc4a.png)

**Comment by sdras** [comment]
Sorry, just so I understand what the problem is- you can't click on the hamburger menu again and make it go away? That's the intended functionality, it's fairly barebones

**Comment by sdras** [comment]
this should be fixed!
